### ISSUE TITLE
Infinite Loop causing 100% CPU

### ISSUE THREAD

**Issue by shibaobun** [yupix/Mi.py#102]
**Describe the bug**
Hello, I've been noticing an extremely intermittent bug where a Mi.py application ends up using 100% CPU, which occurs only randomly some time after application has been running. After using `python -m trace`, I was able to find that the loop happens in `client.py:266` here: https://github.com/yupix/Mi.py/blob/dc072cbd0823cc06e8262a77f770034f69d6c773/mi/framework/client.py#L266

Given that the trace displays `return WS_CLOSED_MESSAGE`, I'm guessing this is when the websocket is accidentally interrupted or closed and needs to be opened again, but I"m not exactly sure

**To Reproduce**
1. Run a Mi.py app for a while
2. Something happens to cause the loop
3. `python -m trace` prints out loop

**Expected behavior**
Mi.py app should restart the websocket connection

**Screenshots**
![2022-03-24_16-03-1648154995](https://user-images.githubusercontent.com/73508390/160008498-6a3c5b4a-3f16-41d1-b278-b994f15e76af.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux, latest LTS Kernel, Python in Docker container
 - v3.9.9

**Comment by yupix** [comment]
We apologize for any inconvenience caused. Could you please upload the traceback as is to [pastebin](https://pastebin.com/) or something similar, instead of screenshotting it, so we can investigate further?

**Comment by yupix** [comment]
In implementing WebSocket reconnection, it is necessary to reconnect to the channel in order to reconnect. To leave this to the user, add a new event, `on_recconect`.

**Comment by yupix** [comment]
We have only handled `WS_CLOSED_MESSAGE` this time as a case where WebSocket reconnection is necessary, but please let us know if you encounter any other errors in the future. If the server goes down during this process, the BOT will not generate any errors. It will automatically reconnect to the server when it becomes available. It is very poorly made. So I hope to add more options when I have more time.

**Comment by yupix** [comment]
Fixed version v3.9.91 has been released. We would appreciate it if you could check if the bugs have been fixed. Also, please refer to the following location for an example of the `on_reconnect` event I wrote earlier.

https://github.com/yupix/Mi.py/blob/626c5bf0420a096e305fcd7ce1acf0de20942864/examples/cog_example/main.py#L39

https://pypi.org/project/mi.py/3.9.91/

**Comment by shibaobun** [comment]
Hello, I just wanted to confirm that this fixed the 100% cpu bug for me, after implementing it in the app. Thank you so much!!!

**Comment by yupix** [comment]
You're welcome, and thank you too for reporting the bug.
