### ISSUE TITLE
potential future feature?

### ISSUE THREAD

**Issue by Tarcaxoxide** [yupix/Mi.py#103]
I'd love for the ability to provide images via local directory and have the bot upload this image along with the text.
or perhaps have an object that can contain both image and text to be sent and then i can manually load the image into the object before sending it.

I'd attempt this myself if i was perhaps a little more familiar with the code base and misskey's api but i just begun tinkering with it.

**Comment by yupix** [comment]
The ability to upload images from local actually existed in the v1.0.0 era, but was removed once due to major refactoring, etc. and is currently awaiting re-implementation. I will try to implement it this week. Thanks for your requests!

**Comment by yupix** [comment]
I practically just pushed to master by mistake, but I think that once mi.py is uninstalled, MiFile can be used by using the following command.

```bash
pip install git+https://github.com/yupix/Mi.py.git
````
