### ISSUE TITLE
`Note` can't be imported

### ISSUE THREAD

**Issue by fotoente** [yupix/Mi.py#96]
**Describe the bug**
When starting a bot with the framework it just thrwos the error
```
Traceback (most recent call last):
  File "/home/ente/roboduck/rdbot.py", line 10, in <module>
    from mi import Note
ImportError: cannot import name 'Note' from 'mi' (/home/ente/.local/lib/python3.9/site-packages/mi/__init__.py)
```

**To Reproduce**
1. Update to Mi.py 3.9.9
2. Start a bot that worked on Mi.py 3.2.1

**Expected behavior**
Bot starts

**Behaviour**
Error right at the start up...

**Comment by yupix** [comment]
As I already answered in the chat, the import has been changed. So, `from mi.framework import Note` should solve the problem.

**Comment by yupix** [comment]
If that doesn't work, try `from mi.framework.models import Note`. If that doesn't work either, please report again.

**Comment by yupix** [comment]
It's currently a problem that can be solved with `from mi.framework.models import Note`, but I'm considering going back to `from mi import Note`. The reason for this is that import becomes longer.

**Comment by yupix** [comment]
To be honest, I'm not sure if I should change this back or keep it the way it is. So, if you have any opinions, please open a discussion.

**Comment by yupix** [comment]
Looks good, so I'll close it.
